# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: 'replicon-expenser-server/Dockerfile'
        tags: |
          replicon-expenser-server:$(tag)
    - task: Docker@2
      displayName: Push an image
      inputs:
        command: push
        tags: |
          appsregistry.azurecr.io/replicon-expenser-server:$(tag)