
trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and push image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    # Docker
    - task: Docker@2
      inputs:
        containerRegistry: 'Apps Container Registry'
        repository: 'replicon-expenser-api'
        command: 'buildAndPush'
        Dockerfile: 'replicon-expenser-server/Dockerfile'
    # Build a Docker image 
    # https://docs.microsoft.com/azure/devops/pipelines/languages/docker
