
trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and push image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    # Docker
    - task: Docker@2
      inputs:
        containerRegistry: 'Apps Container Registry'
        repository: 'replicon-expenser-api'
        command: 'buildAndPush'
        Dockerfile: 'replicon-expenser-server/Dockerfile'
        tags: '$(tag)'
- stage: Deploy
  displayName: Deploy docker container to Azure App Service
  jobs:  
  - job: Release
    displayName: Release
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Visual Studio Enterprise with MSDN (56f0fde1-b4cf-400d-bbbb-a494b6421a7a)'
        appType: 'webAppContainer'
        WebAppName: 'replicon-expenser-api'
        DockerRepository: 'replicon-expenser-api'
        DockerImageTag: '$(tag)'